// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBRYa5_C5-6xS3hb-5PCvKE-DlMGZ1Flm4',
    appId: '1:1061078500537:web:e291808148e41dbccb8768',
    messagingSenderId: '1061078500537',
    projectId: 'flutterpago',
    authDomain: 'flutterpago.firebaseapp.com',
    storageBucket: 'flutterpago.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCjg13QLHwaxRBnsxi0YG7eUsT-oJOUU6Q',
    appId: '1:1061078500537:android:1c05bc86138c1ce2cb8768',
    messagingSenderId: '1061078500537',
    projectId: 'flutterpago',
    storageBucket: 'flutterpago.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBbogVyx7cXfX3Kqx1-uu-KdB9mOTrAUH0',
    appId: '1:1061078500537:ios:43b38eefdefe289ecb8768',
    messagingSenderId: '1061078500537',
    projectId: 'flutterpago',
    storageBucket: 'flutterpago.appspot.com',
    iosBundleId: 'com.example.flutterApplicationPagoplux',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBbogVyx7cXfX3Kqx1-uu-KdB9mOTrAUH0',
    appId: '1:1061078500537:ios:fb68492545e72513cb8768',
    messagingSenderId: '1061078500537',
    projectId: 'flutterpago',
    storageBucket: 'flutterpago.appspot.com',
    iosBundleId: 'com.example.flutterApplicationPagoplux.RunnerTests',
  );
}
